[build]
	publish = "dist"
	command = "node ./scripts/create-token.js && npm run build"

# Fixes 404 errors while using a router + Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200